# https://travis-ci.org/ryanss/bdateutil

language: python

python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.4
    - pypy

install:
    - pip install python-dateutil
    - pip install coveralls

script:
    - coverage run --omit=*site-packages*,*pypy* tests.py

after_success:
    - coveralls
